- name: Create a new database with name 'mysql_db'
  mysql_db:
    name: "{{ mysqldb_database }}"
    state: present
    login_user: root
    login_password: "{{ mysqldb_root_password }}"

- name: Create database user
  mysql_user:
    login_user: root
    login_password: "{{ mysqldb_root_password }}"
    name: "{{ mysqldb_user }}"
    password: "{{ mysqldb_password }}"
    priv: '{{ mysqldb_database }}.*:ALL,GRANT'
    state: present
    host: '%'
  run_once: true
