
  - name: install epel
    yum:
      name: ['epel-release']
      state: installed
    become: yes

  - name: install soft
    yum:
      name: ['python-devel', 'python-pip', 'curl', 'wget', 'iproute', 'sudo']
      state: installed
    become: yes


  - name: Ensure directory for ansible facts exists
    file: state=directory recurse=yes path=/etc/ansible/facts.d/
    become: yes
    become_user: root
