- name: Installing webapp-server
  hosts: web-server

  vars:
    webapp_user: webapp-server
    webapp_group: webapp-server
    webapp_url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/webapp-server/webapp-server
    webapp_home: /opt/webapp-server

    student_first_name: Sergey
    student_last_name: Kosolapov
    http_port: 8080

  tasks:
    - name: Create webapp Group
      group:
        name: "{{ webapp_group }}"
      become: yes

    - name: Add user "webapp"
      user:
        name: "{{ webapp_user }}"
        group: "{{ webapp_group }}"
        home: "{{ webapp_home }}"
        createhome: no
      become: yes

    - name: Create a directory /opt/webapp-server/bin/ if it does not exist
      file:
        path: "{{ webapp_home }}/bin/"
        state: directory
        owner: "{{ webapp_user }}"
        group: "{{ webapp_group }}"
      become: yes

    - name: Create a directory /opt/webapp-server/conf/ if it does not exist
      file:
        path: "{{ webapp_home }}/conf/"
        state: directory
        owner: "{{ webapp_user }}"
        group: "{{ webapp_group }}"
      become: yes

    - name: Download WebApp
      get_url:
        url: "{{ webapp_url }}"
        dest: "{{ webapp_home }}/bin/"
        checksum: "md5:66E5A7366408E9DB471E3E9586E01708"
        mode: 'u+x'
        owner: "{{ webapp_user }}"
        group: "{{ webapp_group }}"
      become: yes

    - name: Copy Configuration File
      template:
        src: webapp-server.conf.j2
        dest: "{{ webapp_home }}/conf/webapp-server.conf"
        owner: "{{ webapp_user }}"
        group: "{{ webapp_group }}"
      notify: webapp-server restart
      become: yes

    - name: Copy WebApp Service File
      template:
        src: webapp-server.service.j2
        dest: /usr/lib/systemd/system/webapp-server.service
      become: yes

    - name: Enable and start WebApp service
      systemd:
        name: webapp-server
        state: started
        enabled: yes
      become: yes

  handlers:
    - name: webapp-server restart
      systemd:
        name: webapp-server
        state: restarted
      become: yes
