webapp_server_user: webapp_server
webapp_server_group: "{{ webapp_server_user }}"
webapp_server_home: /opt/webapp-server
webapp_server_port: 8080
webapp_server_logo_url: https://pridprom.by/images/4/6/a/b/b/46abb83bdc35dfb51a762f31892753a70df19ac7.jpg
webapp_server_student_name: "Sergey Kosolapov"
webapp_server_url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/webapp-server/webapp-server
